[project]
name = "nexrpg"

[[service]]
name = "server"
type = "docker"
path = "server"
port = 3000

[[service]]
name = "client"
type = "static"
path = "client"
buildCommand = "npm run build"
outputDir = "dist"
port = 80
